global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "apache_exporter"
    scrape_interval: 1m
    static_configs:
      - targets: ['177.0.0.1:9117']  # apache exporter is listening on port 9117
